// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package voice

import (
	"context"

	"github.com/google/uuid"
)

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, type, created_at FROM rooms WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listVoiceRooms = `-- name: ListVoiceRooms :many
SELECT id, name, type, created_at FROM rooms WHERE type = 'voice' ORDER BY name ASC
`

func (q *Queries) ListVoiceRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listVoiceRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
