// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package room

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, created_by, has_voice, staff_only)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, updated_at, created_by, has_voice, staff_only
`

type CreateRoomParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
	HasVoice  bool        `json:"has_voice"`
	StaffOnly bool        `json:"staff_only"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Name,
		arg.CreatedBy,
		arg.HasVoice,
		arg.StaffOnly,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.HasVoice,
		&i.StaffOnly,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :one
DELETE FROM rooms
WHERE id = $1
RETURNING id, name, created_at, updated_at, created_by, has_voice, staff_only
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, deleteRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.HasVoice,
		&i.StaffOnly,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, created_at, updated_at, created_by, has_voice, staff_only
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.HasVoice,
		&i.StaffOnly,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role
FROM users
WHERE id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, created_at, updated_at, created_by, has_voice, staff_only
FROM rooms
ORDER BY name ASC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.HasVoice,
			&i.StaffOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $1,
    staff_only = COALESCE($2::boolean, staff_only),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, created_at, updated_at, created_by, has_voice, staff_only
`

type UpdateRoomParams struct {
	Name      string      `json:"name"`
	StaffOnly pgtype.Bool `json:"staff_only"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.Name, arg.StaffOnly, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.HasVoice,
		&i.StaffOnly,
	)
	return i, err
}
