// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package chat

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, content, created_at
`

type CreateMessageParams struct {
	RoomID  uuid.UUID `json:"room_id"`
	UserID  uuid.UUID `json:"user_id"`
	Content string    `json:"content"`
}

type CreateMessageRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.RoomID, arg.UserID, arg.Content)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, type)
VALUES ($1, $2)
RETURNING id, name, type, created_at
`

type CreateRoomParams struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.Type)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByRoom = `-- name: GetMessagesByRoom :many
SELECT
    m.id,
    m.content,
    m.created_at,
    u.id AS user_id,
    u.username
FROM messages m
JOIN users u ON m.user_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type GetMessagesByRoomParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Limit  int32     `json:"limit"`
}

type GetMessagesByRoomRow struct {
	ID        uuid.UUID          `json:"id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    uuid.UUID          `json:"user_id"`
	Username  string             `json:"username"`
}

func (q *Queries) GetMessagesByRoom(ctx context.Context, arg GetMessagesByRoomParams) ([]GetMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByRoom, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByRoomRow
	for rows.Next() {
		var i GetMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, type, created_at
FROM rooms
ORDER BY name ASC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, room_id, content, updated_at
`

type UpdateMessageParams struct {
	Content string    `json:"content"`
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
}

type UpdateMessageRow struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	Content   string             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (UpdateMessageRow, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.Content, arg.ID, arg.UserID)
	var i UpdateMessageRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
